config/routes.rb
Rails.application.routes.draw do

  root    'session#new'

  get     'login'        =>  'session#new'
  post    'login'        =>  'session#create'
  delete  'logout'       =>  'session#destroy'
  get     'signup'       =>  'users#new'
  get     'search'       =>  'projects#search'
  get     'profile'      =>  'users#profile'

  get     'users/graph'
  get     'sales_channels/get_data' => 'sales_channels#get_data', :defaults => { :format => 'json' }

  resources :time_entries, except: [:new, :create] do
    collection do
      post  'clock_in'
      patch 'clock_out'
    end
  end
  resources :project_costs do
    collection do
      get 'search'
    end
  end
  resources :material_uses
  resources :material_purchases do
    collection do
      get 'search'
    end
  end
  resources :sales_channels do
    collection do
      get 'search'
    end
  end
  resources :business_expenses do
    collection do
      get 'search'
    end
  end
  resources :sales_goals
  resources :sales do
    collection do
      get 'search'
    end
  end
  resources :projects do
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get 'dashboard'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :material_purchases do
    def in_stock
      where("units_remaining > 0")
    end
  end
  has_many :material_uses
  has_many :project_costs
  has_many :sales
  has_many :sales_goals
  has_many :sales_channels
  has_many :material_uses
  has_many :project_costs
  has_many :sales
  has_secure_password
  has_attached_file :avatar, styles: { medium: "300x300>#", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :name, presence: true
  validates :email, presence: true,
      uniqueness: { case_sensitive: false },
      format: {
        with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
        message: "Not a valid email address",
        on: :create
      }
  validates :password, length: { minimum: 8 }, allow_nil: true
  validates :hourly_rate, presence: true, numericality: {greater_than: 0}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :dashboard]
  before_action :require_login, except: [:new, :create]
  layout "signup", :only => [:new]

  def profile
    @sales = Sale.where(user_id: @current_user.id)
  end

  def index
    redirect_to profile_path
  end

  def show
    redirect_to profile_path
  end
  # GET /users/new
  def new
    redirect_to dashboard_user_path(session[:user_id]) if logged_in?
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to dashboard_user_path(session[:user_id]) if @user != @current_user
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to profile_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to profile_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def dashboard
    redirect_to dashboard_user_path(@user.id) unless @user == @current_user
    @projects = Project.where('user_id = ?', @user.id).order(updated_at: :desc).limit(5)
    @sales = Sale.where('user_id = ?', @user.id).order(date: :desc, created_at: :desc).limit(5)
    @goal = SalesGoal.where('user_id = ?', @user.id).last
    if @user.sales_goals.length > 0
      @percent_completion = SalesGoal.percent_completion(@goal)
    else
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      begin
        @user = User.find(params[:id])
      rescue
        redirect_to login_path
      end
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :public_profile, :time_zone, :hourly_rate, :avatar)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="login-boxes">
<%= form_for @user, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <p>
          <%= f.label :name %>
          <%= f.text_field :name, value: @user.name || "" %>
        </p>
        <p>
          <%= f.label :email %>
          <%= f.text_field :email, value: @user.email || "" %>
        </p>
        <% if !logged_in? %>
        <p>
          <%= f.label :password %>
          <%= f.password_field :password %>
        </p>
        <% else %>
        <% end %>
        <p>
          <%= f.label :hourly_rate %>
          <%= f.number_field :hourly_rate, :class => 'text_field', :step => 0.01 %>
        </p>
        <% if logged_in? %>
        <p>
          <%= f.label :update_avatar %>
          <%= f.file_field :avatar %>
        </p>
        <% else %>
        <% end %>

        <p>
          <%= f.submit 'Submit' %>
        </p>
      <% end %>
    </div>

app/views/users/dashboard.html.erb
<div class="title"><%= link_to (image_tag asset_url('home.png'), class: "card-header-icon"), root_path %>Dashboard</div>
<div class="cards">

  <div class="card start-of-line">
    <% if @user.sales_goals.length > 0 %>
      <div class="card-image">
        <div class="donut-graph" data-percentage="<%= @percent_completion %>"></div>
      </div>
      <div class="card-copy">
        <p>Goal: <%= "#{number_to_currency(@goal.amount)} in sales by #{@goal.end_time.strftime("%B %d, %Y")}" %></p>
      </div>
    <% else %>
      <div class="card-image">
      </div>
      <div class="card-copy">
        <p><%= link_to 'Add a Sales Goal', new_sales_goal_path %></p>
      </div>
    <% end %>
  </div>

  <div class="card end-of-line">
    <div class="card-image">
      <div id="pieChart"></div>
    </div>
    <div class="card-copy">
      <p>Active Sales Channels</p>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <h1><%= link_to (image_tag asset_url('p1.png'), class: "card-header-icon"), projects_path %><%= link_to 'My Projects', projects_path %></h1>
    </div>
    <div class="card-copy">
      <% if @projects.length > 0 %>
        <% @projects.each do |project| %>
          <p><%= link_to project.name, project %></p>
        <% end %>
      <p><%= link_to '(See All)', projects_path %></p>
    <% else %>
      <p><%= link_to 'Create a Project', new_project_path %></p>
    <% end %>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <h1><%= link_to (image_tag asset_url('sales.png'), class: "card-header-icon"), sales_path %><%= link_to 'My Sales', sales_path %></h1>
    </div>
    <div class="card-copy">
      <% if @sales.length > 0 %>
        <% @sales.each do |sale| %>
          <p><%= link_to sale.project.name, sale %>: <%= number_to_currency(sale.gross) %></p>
        <% end %>
      <p><%= link_to '(See All)', sales_path %></p>
    <% else %>
      <p><%= link_to 'View Projects', projects_path %></p>
    <% end %>
    </div>
  </div>

</div>

app/views/users/edit.html.erb
<div class="title">Edit Your Details</div>

<%= render 'form' %>

<div class="form-lower-buttons">
  <h3>
    <%= link_to 'Back to Profile', users_path %>
  </h3>
</div>

app/views/users/new.html.erb
    <div class="background-ghost">
      <div class="cards">
        <div class="smaller-percent">
          <div class="card">
            <div class="some-height-padding login">
              <h1>Sign Up</h1>
              <div class="login-boxes">
              <%= render 'form' %>
              <p>For existing users, log in <%= link_to "here", login_path %></p>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/profile.html.erb
      <div class="profile-image-column">
        <%= image_tag @current_user.avatar.url(:medium), class: "profile-image" %>
      </div>
      <div class="profile-middle-column">
        <h1><%= @current_user.name %></h1>
        <p><%= @current_user.email %></p>
        <p><%= number_to_currency(@current_user.hourly_rate) %>/hour</p>
        <p><%= link_to (image_tag asset_url('edit.png'), size: "20x20"), edit_user_path(@current_user) %></p>
      </div>
      <div class="profile-right-column">
        <p><label class="stat-label">Sales:</label> <%= @sales.count %></p>
        <p><label class="stat-label">Projects:</label> <%= @current_user.projects.count %></p>
        <p><label class="stat-label">Sales goals:</label> <%= @current_user.sales_goals.count %></p>
        <p><label class="stat-label">Goals reached:</label> <%= @current_user.sales_goals.where(success: true).count %></p>
      </div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag asset_url('julie_placeholder.jpg'), class: "julie" %>

<ul class="accordion-tabs-minimal">
  <li class="tab-header-and-content">
    <a href="#" class="tab-link is-active">User Information</a>
    <div class="tab-content">
      <div class="user-information">
      <p>
        <strong>Name:</strong>
        <%= @user.name.upcase %>
      </p>

      <p>
        <strong>E-mail:</strong>
        <%= @user.email %>
      </p>

      <p>
        <%= @user.time_zone %>
      </p>

      <p>
        <%= link_to 'Edit', edit_user_path(@user) %> |
        <%= link_to 'Back', users_path %>
      </p>
      </div>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Projects</a>
    <div class="tab-content">
      <table class="user-projects">
        <thead>
          <tr>
            <th>Name of Piece</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
      <% @user.projects.first(5).each do |project| %>
            <tr>
              <td><%= project.name %></td>
              <td><%= project.description %> </td>
            </tr>
            <%if project.sales.length > 0 %>
              <% project.sales.each do |sale| %>
                <tr>
                  <td>$<%= sale.gross %></td>
                  <td>Sold on: <%= sale.date %> </td>
                </tr>
              <% end %>
            <% else %>
                  <tr>
                    <td>Email for details</td>
                    <td>Avalible for purchase</td>
                  </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Last Item</a>
    <div class="tab-content">
      <p>I'm awesome</p>
    </div>
  </li>
</ul>