config/routes.rb
Rails.application.routes.draw do

  root    'session#new'

  get     'login'        =>  'session#new'
  post    'login'        =>  'session#create'
  delete  'logout'       =>  'session#destroy'
  get     'signup'       =>  'users#new'
  get     'search'       =>  'projects#search'
  get     'profile'      =>  'users#profile'

  get     'users/graph'
  get     'sales_channels/get_data' => 'sales_channels#get_data', :defaults => { :format => 'json' }

  resources :time_entries, except: [:new, :create] do
    collection do
      post  'clock_in'
      patch 'clock_out'
    end
  end
  resources :project_costs do
    collection do
      get 'search'
    end
  end
  resources :material_uses
  resources :material_purchases do
    collection do
      get 'search'
    end
  end
  resources :sales_channels do
    collection do
      get 'search'
    end
  end
  resources :business_expenses do
    collection do
      get 'search'
    end
  end
  resources :sales_goals
  resources :sales do
    collection do
      get 'search'
    end
  end
  resources :projects do
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get 'dashboard'
    end
  end

end

app/models/project_cost.rb
class ProjectCost < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates :cost_type, presence: true
  validates :amount, presence: true, numericality: {greater_than: 0}

  # def self.search(q, user_id)
  #   projects = Project.where("user_id = ? AND name LIKE ?", user_id, q)
  #   project_costs = ProjectCost.includes(:project).where("cost_type LIKE ?", q)
  #   project_costs = project_costs.select{|cost| cost.project.user_id == user_id}
  #   projects += project_costs.map{|cost| cost.project}
  #   projects
  # end

  def self.search(pc, q)
    search = "%#{q}%"
    project_costs_search = Project.where(id: pc.where("cost_type LIKE LOWER(?)", search).pluck(:project_id)).arel.constraints.reduce(:and)
    project_search = Project.search(q).arel.constraints.reduce(:and)
    Project.where(project_search.or(project_costs_search))
  end
end

app/controllers/project_costs_controller.rb
class ProjectCostsController < ApplicationController
  before_action :require_login
  before_action :set_project_cost, only: [:destroy]

  # GET /project_costs
  def index
    if params[:search]
      pc = project_cost_scope
      @projects = ProjectCost.search(pc, params[:search])
    else
      @projects = Project.where(user_id: @current_user.id)
    end
  end

  # # GET /project_costs/1
  # def show
  # end
  #
  #
  # # GET /project_costs/1/edit
  # def edit
  # end
  #
  # # POST /project_costs
  # def create
  #   @project_cost = ProjectCost.new(project_cost_params)
  #   @project_cost.user_id = @current_user.id
  #   if @project_cost.save
  #     redirect_to @project_cost, notice: 'Project cost was successfully created.'
  #   else
  #     render :new
  #   end
  # end
  #
  # # PATCH/PUT /project_costs/1
  # def update
  #   if @project_cost.update(project_cost_params)
  #     redirect_to @project_cost, notice: 'Project cost was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  # DELETE /project_costs/1
  def destroy
    @project_cost.destroy
    redirect_to project_costs_url, notice: 'Project cost was successfully destroyed.'
  end

  private
    # So that people cannot PATCH and DELETE unless they are the @current_user
    def project_cost_scope
      ProjectCost.where(user_id: @current_user.id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project_cost
      begin
        @project_cost = project_cost_scope.find(params[:id])
        # @project_cost = ProjectCost.find(params[:id])
      rescue
        redirect_to dashboard_user_path(@current_user.id), notice: "Not found."
      end
    end

    # Only allow a trusted parameter "white list" through.
    def project_cost_params
      params.require(:project_cost).permit(:project_id, :cost_type, :amount)
    end
end

app/helpers/project_costs_helper.rb
module ProjectCostsHelper
end

app/views/project_costs/_form.html.erb
<%= form_for(@project_cost) do |f| %>
  <% if @project_cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_cost.errors.count, "error") %> prohibited this project_cost from being saved:</h2>

      <ul>
      <% @project_cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :project_id, value: @project_cost.project_id || params[:project_id] %>
  </div>
  <div class="field">
    <%= f.label :cost_type %><br>
    <%= f.text_field :cost_type, value: @project_cost.cost_type || ""%>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount, :class => 'text_field', :step => 0.01, value: number_to_currency(@project_cost.amount) || ""%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_costs/edit.html.erb
<div class="title">Edit Project Cost</div>

<%= render 'form' %>

<div class="form-lower-buttons">
  <h3>
    <%= link_to 'Details', @project_cost %>
    <%= link_to 'Back to Project Costs', project_costs_path %>
    <%= link_to 'Delete This Cost', project_cost_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" %>
  </h3>
</div>

app/views/project_costs/index.html.erb
<div class="title">
  <%= image_tag asset_url('costs.png'), class: "card-header-icon" %>Project Costs Breakdowns
  <%= form_tag project_costs_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder:"Enter Search" %>
  <%= image_submit_tag "search.png", class: "search-button", name: nil %>
  <% end %>
</div>

<h3><%= link_to 'Add New Project', new_project_path %> <%= link_to 'See All Projects', projects_path %> <%= link_to 'See Sold Projects', projects_path(sold: true) %> </h3>
<% if @projects.length > 0 %>
  <% @projects.each do |project| %>
    <div class="cards">
      <div class="card">
        <div class="card-header">
          <h2>Costs for <%= link_to project.name, project %>:</h2>
          <div class="details">
          <%= link_to (image_tag asset_url('edit.png'), class: "index-icon"), edit_project_path(project) %>
          <%= link_to (image_tag asset_url('destroy.png'), class: "index-icon"), project, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div></br>
            <% if project.material_uses.length > 0 || project.project_costs.length > 0 %>
              <% if project.material_uses.length > 0 %>
                <% project.material_uses.each do |material_use| %>
                  <div class="details">
                    <%= material_use.name %>
                    <%= material_use.units %>
                    <%= number_to_currency(material_use.cost) %>
                  </div>
                <% end %>
              <% else %>
              <% end %>
              <% if project.project_costs.length > 0 %>
                <% project.project_costs.each do |project_cost| %>
                  <div class="details">
                    <%= project_cost.cost_type %>
                    <%= number_to_currency(project_cost.amount) %>
                  </div>
                <% end %></br>
              <% else %>
              <% end %>
            <% else %>
            <div class="details">
              <p>There are no current projects costs.</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
<% end %>

app/views/project_costs/show.html.erb
  <div class="title"><%= @project_cost.cost_type %></div>

  <div class="project-cost-show-amount">Cost: <%= number_to_currency(@project_cost.amount) %></div>

<div class="edit-back">
  <%= link_to 'Edit', edit_project_cost_path(@project_cost) %> |
  <%= link_to 'Back to Project Costs', project_costs_path %>
</div>