config/routes.rb
Rails.application.routes.draw do

  root    'session#new'

  get     'login'        =>  'session#new'
  post    'login'        =>  'session#create'
  delete  'logout'       =>  'session#destroy'
  get     'signup'       =>  'users#new'
  get     'search'       =>  'projects#search'
  get     'profile'      =>  'users#profile'

  get     'users/graph'
  get     'sales_channels/get_data' => 'sales_channels#get_data', :defaults => { :format => 'json' }

  resources :time_entries, except: [:new, :create] do
    collection do
      post  'clock_in'
      patch 'clock_out'
    end
  end
  resources :project_costs do
    collection do
      get 'search'
    end
  end
  resources :material_uses
  resources :material_purchases do
    collection do
      get 'search'
    end
  end
  resources :sales_channels do
    collection do
      get 'search'
    end
  end
  resources :business_expenses do
    collection do
      get 'search'
    end
  end
  resources :sales_goals
  resources :sales do
    collection do
      get 'search'
    end
  end
  resources :projects do
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get 'dashboard'
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :time_entries
  has_many :sales, dependent: :restrict_with_error
  has_many :material_uses
  has_many :project_costs
  validates :name, presence: true
  accepts_nested_attributes_for :material_uses, reject_if: proc { |attributes| attributes['units'].blank? }, allow_destroy: :true
  accepts_nested_attributes_for :project_costs, reject_if: :all_blank, allow_destroy: :true

  def total_time
    # Set a default value for time entry total_time field later
    time_entries.reduce(0.0){|sum, t| sum + (t.total_time || 0)}
  end

  def estimated_value
    total_expenses + time_expense
  end

  def time_expense
    user.hourly_rate * total_time/3600
  end

  def total_expenses
    total_material_cost + total_other_expenses
  end

  def total_material_cost
    # project = Project.joins(:material_uses).where('material_purchase_id' => material_purchases.id).includes(:material_purchases)
    # project.material_uses.where(material_purchase_id: project.user.material_purchases)
    materials = MaterialUse.includes(:material_purchase).where(project_id: id)
    if materials.length > 0
      cost = materials.map{|x|  x.material_purchase.cost}
      units = materials.map{|x|  x.material_purchase.units}
      total_units = materials.map {|x| x.units}

      (cost.sum/units.sum) * total_units.sum
    else
      0
    end
  end

  def total_other_expenses
    if project_costs.length > 0
      project_costs.map{|cost| cost.amount}.reduce(:+)
    else
      0
    end
  end

  def self.search(q)
    search =  "%#{q}%"
    Project.where("projects.name LIKE LOWER(?) OR projects.description LIKE LOWER(?)", search, search)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  after_action  :update_inventory, only: [:create, :update]

  # GET /projects
  def index

    if params[:search]
      @projects = project_scope.search(params[:search])
    elsif params[:sold]
      @projects = project_scope.includes(:sales, :user, :time_entries).order('name').select{|project| project.sales.length > 0}
    else
      @projects = project_scope.includes(:sales, :user, :time_entries).order('name')
    end
  end

  # GET /projects/1
  def show
    @project_time = @project.total_time
    @time_entries = TimeEntry.where('project_id = ?', @project.id).order(:date)
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.material_uses.build
    @project.project_costs.build
  end

  # GET /projects/1/edit
  def edit
    @project.material_uses.build
    @project.project_costs.build
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.user_id = @current_user.id
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      flash[:error] = "Missing required fields"
      redirect_to new_project_path
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      @project.save
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      flash[:error] = "Missing required fields"
      redirect_to edit_project_path
    end
  end

  # DELETE /projects/1
  def destroy
    if @project.destroy
      redirect_to projects_url, notice: 'Project was successfully destroyed.'
    else
      redirect_to projects_url, notice: 'Project cannot be destroyed.'
    end
  end

  private
    # So that people cannot PATCH and DELETE unless they are the @current_user
    def project_scope
      Project.where(user_id: @current_user.id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      begin
        @project = project_scope.find(params[:id])
      rescue
        redirect_to dashboard_user_path(@current_user.id), notice: "Not found."
      end
    end
    def update_inventory
      @project.material_uses.each do |material_use|
        material_use.material_purchase.units_remaining = material_use.material_purchase.update_stock
        material_use.material_purchase.save
      end
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:user_id, :name, :description,
      project_costs_attributes: [:id, :cost_type, :amount, :user_id, :project_id, :_destroy],
      material_uses_attributes: [:id, :material_purchase_id, :project_id, :user_id, :units, :_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="cards">
    <div class="card">
      <div class="card-header"></div>
      <div class="index-card">
        <div>
          <p ><%= f.label :name %></br>

          <%= f.text_field :name, value: @project.name || ""%></p>
        </div>
        <div class="field">
          <p><%= f.label :description %></br>
          <%= f.text_area :description, value: @project.description || ""%></p>
        </div></br>
        <div><h5> Materials: </h5></div>
        <div class="material-form">
          <%= f.fields_for :material_uses do |ff| %>
          <div class = "material-fields">
            <div class="field">
              <p><%= ff.label :material_purchase_id, value: "Material" %>
              <%= ff.collection_select(:material_purchase_id, @current_user.material_purchases.order(:name), :id, :name, {prompt: "Select Material"}) %>
              <%= ff.label :units %>
              <%= ff.number_field :units, step: :any%></p>
            </div>
          </div>
          <% end %>
        </div>
        <button type="button" class="add-material-button">Add Material </button>

        <div><h5> Project Costs: </h5></div>
        <div class="project-cost-form" id="project-cost-form">
          <%= f.fields_for :project_costs do |ff| %>
            <div class = "project-cost-fields">
              <div class="field">
                <p><%= ff.label :cost_type %>
                <%= ff.text_field :cost_type%>
                <%= ff.label :amount %>
                <%= ff.number_field :amount%></p>
              </div>
            </div>
          <% end %>
        </div>
        <button type="button" class="add-project-button">Add Project Cost </button>
        <p />
        <div class="actions">
          <p><%= f.submit %></p>
        </div>
    </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="title">Editing <%= @project.name %></div>

<%= render 'form' %>

      <div class="form-lower-buttons">
        <h3>
        <%= link_to 'Back to Project', @project %>
        <%= link_to 'Back to All Projects', projects_path %>
        <%= link_to 'Delete This Project', project_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" %>
      </h3>
      </div>

app/views/projects/index.html.erb
<div class="title">
<%= image_tag asset_url('p1.png'), class: "card-header-icon" %>My <% if params[:sold] %>Sold<% else %><% end %> Projects
<%= form_tag projects_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder:"Enter Search" %>
  <%= image_submit_tag "search.png", class: "search-button", name: nil %>
<% end %>
</div>
<h3>
  <%= link_to 'Add New Project', new_project_path %>
  <% if !params[:sold] %>
    <%= link_to 'See Sold Projects', projects_path(sold: true) %>
  <% else %>
    <%= link_to 'See All Projects', projects_path %>
  <% end %>
</h3>
<% if @projects.length > 0 %>
  <% @projects.each do |project| %>

  <div class="cards">
    <div class="card">
      <div class="card-header">
        <%= link_to (image_tag asset_url('edit.png'), class: "index-icon"), edit_project_path(project) %>
        <%= link_to (image_tag asset_url('sold.png'), class: "sold-icon"), new_sale_path(project_id: project.id) %>
        <h2><%= link_to project.name, project%></h2>
        <div class="details">
          <br />
          <h3><%=  project.description.capitalize%></h3>
          <h3>Total Revenue: <%= number_to_currency(project.sales.map{|x| x.gross}.sum)%></h3>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% else %>
<% end %>

app/views/projects/new.html.erb
<div class="title">New Project</div>

<%= render 'form' %>

<div class="form-lower-buttons">
  <h3><%= link_to 'Back to Projects', projects_path %></h3>
</div>

app/views/projects/show.html.erb
<div class="title"></div>
<div class="page-wrap">

  <div class="card">
    <div class="project-show-card padding-underload">
      <div class="details">
        <%= link_to (image_tag asset_url('edit.png'), class: "index-icon"), edit_project_path(@project) %>
        <%= link_to (image_tag asset_url('sold.png'), class: "sold-icon"), new_sale_path(project_id: @project.id) %>
        <h2><%= @project.name %></h2>
        <h3><%= @project.description.capitalize %></h3>
      </div>
      <div class="index-card">
        <h4> Materials </h4>
        <% if @project.material_uses.length > 0 %>
          <% @project.material_uses.each do |material| %>
            <h3><%= material.name %></br>
            Units: <%= material.units %></br>
            Cost: <%= number_to_currency(material.cost) %></h3>
          <% end %>
        <% else %>
          <h3>No materials are applied to this project.</h3>
        <% end %>

        <h4>Project Costs</h4>
        <% if @project.project_costs.length > 0 %>
          <% @project.project_costs.each do |cost| %>
            <h3><%= cost.cost_type %></br>
            Cost: <%= number_to_currency(cost.amount) %></h3>
          <% end %>
        <% else %>
          <h3>No costs are applied to this project.</h3>
        <% end %>

      <h4>Sales</h4>
      <div class="index-card">
        <% if @project.sales.length > 0 %>
          <% @project.sales.each do |sale| %>
            <h3>Sold on <%= sale.date.strftime("%B %d, %Y") %> for <%= number_to_currency(sale.gross) %></h3>
          <% end %>
        <% else %>
          <h3>In Stock</h3><br />
          <h3>
            The estimated value of this project is
            <%= number_to_currency(@project.estimated_value)%>
          </h3>
        <% end %>
        <br />
        <h3><%= link_to 'Back to All Projects', projects_path, class: "project-show-buttons" %></h3>
      </div>
    </div>
    </div>
  </div>

  <div class="card">
    <div class="clock-card">
      <div class="card-header">
        <div class="clock-buttons">
          <%= link_to 'Clock In', clock_in_time_entries_path(time_entry: {project_id: @project.id}), method: :post, id: "clock-in" %>
          <%= link_to 'Clock Out', clock_out_time_entries_path(time_entry: {project_id: @project.id}), method: :patch, id: "clock-out" %>
        </div>
        <div class="details">
          <p><% if @project_time > 0 %>
            <h3>You have worked on <%= @project.name %> for
            <%= (@project_time/3600).floor %> hours</h3>
            <% @time_entries.each do |time_entry| %>
              <% if time_entry.start_time && time_entry.stop_time %>
                <h3>
                  <%= distance_of_time_in_words(time_entry.stop_time, time_entry.start_time).capitalize %>
                  worked on <%= link_to time_entry.start_time.strftime("%B %d"), time_entry, id: "time-entry" %>
                </h3>
              <% end %>
            <% end %>
            <br />
            <h3><%= link_to 'View All Time Entries', time_entries_path(id: @project.id), class: "project-show-buttons"%></h3>
          <% else %>
              You have not worked on this project yet.
          <% end%>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>