config/routes.rb
Rails.application.routes.draw do

  root    'session#new'

  get     'login'        =>  'session#new'
  post    'login'        =>  'session#create'
  delete  'logout'       =>  'session#destroy'
  get     'signup'       =>  'users#new'
  get     'search'       =>  'projects#search'
  get     'profile'      =>  'users#profile'

  get     'users/graph'
  get     'sales_channels/get_data' => 'sales_channels#get_data', :defaults => { :format => 'json' }

  resources :time_entries, except: [:new, :create] do
    collection do
      post  'clock_in'
      patch 'clock_out'
    end
  end
  resources :project_costs do
    collection do
      get 'search'
    end
  end
  resources :material_uses
  resources :material_purchases do
    collection do
      get 'search'
    end
  end
  resources :sales_channels do
    collection do
      get 'search'
    end
  end
  resources :business_expenses do
    collection do
      get 'search'
    end
  end
  resources :sales_goals
  resources :sales do
    collection do
      get 'search'
    end
  end
  resources :projects do
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get 'dashboard'
    end
  end

end

app/views/layouts/_awesome_footer.html.erb
<footer class="site-footer">
  View the ArtTrack source code <a href="https://github.com/arttrackd/arttrackd">here.</a>
</footer>

app/views/layouts/_navbar.html.erb
<header class="navigation" role="banner">
  <div class="navigation-left">
    <%= link_to 'ArtTrack', root_path, class: "logo" %>
  </div>
  <% if logged_in? %>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if clocked_in? %>
          <li class = "nav-link stopwatch-text">Working on <%= truncate(@current_time_entry.project.name) %> for
          <span class="stopwatch" id="timer" start-time="<%=@current_time_entry.start_time.to_f * 1000 %>"></span></li>
          <li class="nav-link"><%= link_to 'Clock Out', clock_out_time_entries_path(time_entry: {project_id: @current_time_entry.project_id}), method: :patch, id: "clock-out-nav" %></li>
        <% end %>
        <div class="navigation-right">
          <%= link_to 'Log Out', logout_path, method: :delete %>
        </div>
      </ul>
    </nav>
  <% end %>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-column">
  <div class="profile-img-padding">
    <%= link_to (image_tag @current_user.avatar.url(:medium), class: "profile-image", alt: "Profile Picture"), profile_path %>
  </div>
  <div class="sidebar-center"><%= link_to @current_user.name, profile_path %></div></br>
  <div class="highlight-left-border sidebar-link">
    <%= link_to (image_tag asset_url('home.png'), class: "sidebar-icon"), root_path %><%= link_to 'Dashboard', root_path, class: "fix-centering" %>
  </div>
  <div class="highlight-left-border sidebar-link">
    <%= link_to (image_tag asset_url('p1.png'), class: "sidebar-icon"), projects_path %><%= link_to 'My Projects', projects_path, class: "fix-centering" %>
  </div>
  <div class="highlight-left-border sidebar-link">
    <%= link_to (image_tag asset_url('p2.png'), class: "sidebar-icon"), material_purchases_path %><%= link_to 'My Inventory', material_purchases_path, class: "fix-centering" %>
  </div>
  <div class="highlight-left-border sidebar-link">
    <%= link_to (image_tag asset_url('goals.png'), class: "sidebar-icon"), sales_goals_path %><%= link_to 'My Goals', sales_goals_path, class: "fix-centering" %>
  </div>
  <div class="highlight-left-border sidebar-link">
    <%= link_to (image_tag asset_url('sales.png'), class: "sidebar-icon"), sales_path %><%= link_to 'My Sales', sales_path, class: "fix-centering" %>
  </div>
  <div class="highlight-left-border sidebar-link">
    <%= link_to (image_tag asset_url('costs.png'), class: "sidebar-icon"), business_expenses_path %><%= link_to 'My Costs', business_expenses_path, class: "fix-centering" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arttrack</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="page-wrap blue">
      <%= render 'layouts/sidebar' %>

      <div class="dashboard-right">
        <% if flash[:notice] %>
          <div class="flash-shift flash-notice"><%= flash[:notice] %></div>
        <% end %>
        <% if flash[:alert] %>
          <div class="flash-shift flash-alert"><%= flash[:alert] %></div>
        <% end %>
        <% if flash[:warning] %>
          <div class="flash-shift flash-warning"><%= flash[:warning] %></div>
        <% end %>
        <% if flash[:error] %>
          <div class="flash-shift flash-error"><%= flash[:error] %></div>
        <% end %>
        <% if flash[:success] %>
          <div class="flash-shift flash-success"><%= flash[:success] %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/awesome_footer' %>
  </body>
</html>

app/views/layouts/dashboard_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arttrackd</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert"><%= flash[:alert] %></div>
      <% end %>
      <% if flash[:warning] %>
        <div class="warning"><%= flash[:warning] %></div>
      <% end %>
      <% if flash[:error] %>
        <div class="error"><%= flash[:error] %></div>
      <% end %>
      <% if flash[:success] %>
        <div class="success"><%= flash[:success] %></div>
      <% end %>
        <%= yield %>
  <%= render 'layouts/awesome_footer' %>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arttrack</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert"><%= flash[:alert] %></div>
      <% end %>
      <% if flash[:warning] %>
        <div class="warning"><%= flash[:warning] %></div>
      <% end %>
      <% if flash[:error] %>
        <div class="error"><%= flash[:error] %></div>
      <% end %>
      <% if flash[:success] %>
        <div class="success"><%= flash[:success] %></div>
      <% end %>
        <%= yield %>
        <%= link_to (image_tag asset_url('clay.jpeg'), class: "login-image") %>
    <%= render 'layouts/awesome_footer' %>
  </body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arttrack</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert"><%= flash[:alert] %></div>
      <% end %>
      <% if flash[:warning] %>
        <div class="warning"><%= flash[:warning] %></div>
      <% end %>
      <% if flash[:error] %>
        <div class="error"><%= flash[:error] %></div>
      <% end %>
      <% if flash[:success] %>
        <div class="success"><%= flash[:success] %></div>
      <% end %>
        <%= yield %>
        <%= link_to (image_tag asset_url('clay.jpg'), class: "login-image") %>
  <%= render 'layouts/awesome_footer' %>
  </body>
</html>